name: xmake on ubuntu-24.04

on:
  push:
    branches: [ ci-workflow ]
  pull_request:
    branches: [ ci-workflow ]

jobs:
  build:
    runs-on: ubuntu-24.04       

    steps:
    - uses: actions/checkout@v4
    
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Configure xmake
      run: >
        xmake f -y 
        --cc=gcc-14
        --cxx=g++-14
        --mode=Release

    - name: Build
      run: xmake

    - name: Test
      run: xmake test
